//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 04:34:28 PM EEST 
//


package bg.bozho.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldOperation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FieldOperation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Add"/>
 *     &lt;enumeration value="Erase"/>
 *     &lt;enumeration value="Current"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FieldOperation")
@XmlEnum
public enum FieldOperation {


    /**
     * 
     *             \u041f\u043e\u043b\u0435\u0442\u043e \u0435 \u0434\u043e\u0431\u0430\u0432\u0435\u043d\u043e \u0438\u043b\u0438 \u043f\u043e \u043d\u0435\u0433\u043e \u0435 \u043d\u0430\u043f\u0440\u0430\u0432\u0435\u043d\u0430 \u043f\u0440\u043e\u043c\u044f\u043d\u0430.
     *           
     * 
     */
    @XmlEnumValue("Add")
    ADD("Add"),

    /**
     * 
     *             \u041f\u043e\u043b\u0435\u0442\u043e \u0435 \u0438\u0437\u0442\u0440\u0438\u0442\u043e.
     *           
     * 
     */
    @XmlEnumValue("Erase")
    ERASE("Erase"),

    /**
     * 
     *             \u041f\u043e\u043b\u0435\u0442\u043e \u0435 \u043d\u0435\u043f\u0440\u043e\u043c\u0435\u043d\u0435\u043d\u043e.
     *           
     * 
     */
    @XmlEnumValue("Current")
    CURRENT("Current");
    private final String value;

    FieldOperation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldOperation fromValue(String v) {
        for (FieldOperation c: FieldOperation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
