//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 04:34:28 PM EEST 
//


package bg.bozho.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PackageType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="New"/>
 *     &lt;enumeration value="ForChange"/>
 *     &lt;enumeration value="Preregistration"/>
 *     &lt;enumeration value="Transformation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PackageType", namespace = "http://www.registryagency.bg/schemas/deedv2")
@XmlEnum
public enum PackageType {


    /**
     * 
     * 									   \u041f\u0430\u043a\u0435\u0442\u0430 \u0435 \u043f\u043e\u0434\u0430\u0434\u0435\u043d \u0437\u0430 \u043f\u044a\u0440\u0432\u043e\u043d\u0430\u0447\u0430\u043b\u043d\u0430 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f.
     * 								   
     * 
     */
    @XmlEnumValue("New")
    NEW("New"),

    /**
     * 
     * 									   \u041f\u0430\u043a\u0435\u0442\u0430 \u0435 \u043f\u043e\u0434\u0430\u0434\u0435\u043d \u0437\u0430 \u043f\u0440\u043e\u043c\u044f\u043d\u0430.
     * 								   
     * 
     */
    @XmlEnumValue("ForChange")
    FOR_CHANGE("ForChange"),

    /**
     * 
     * 									   \u041f\u0440\u0435\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f.
     * 								   
     * 
     */
    @XmlEnumValue("Preregistration")
    PREREGISTRATION("Preregistration"),
    @XmlEnumValue("Transformation")
    TRANSFORMATION("Transformation");
    private final String value;

    PackageType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PackageType fromValue(String v) {
        for (PackageType c: PackageType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
