//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 04:34:28 PM EEST 
//


package bg.bozho.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.registryagency.bg/schemas/deedv2/Fields}RecordCommonAttributes"/>
 *       &lt;attribute name="ActModeText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ActModeValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ActID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ActDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ActYear" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ActWithErasedPersonalData" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementType")
@XmlSeeAlso({
    bg.bozho.model.StatementsAM.StatementAM.class,
    bg.bozho.model.StatementsAL.StatementAL.class,
    bg.bozho.model.StatementsAK.StatementAK.class,
    bg.bozho.model.StatementsAJ.StatementAJ.class,
    bg.bozho.model.StatementsAI.StatementAI.class,
    bg.bozho.model.StatementsAH.StatementAH.class,
    bg.bozho.model.StatementsAG.StatementAG.class,
    bg.bozho.model.StatementsAF.StatementAF.class,
    bg.bozho.model.StatementsAE.StatementAE.class,
    bg.bozho.model.StatementsAD.StatementAD.class,
    bg.bozho.model.StatementsAC.StatementAC.class,
    bg.bozho.model.StatementsAB.StatementAB.class,
    bg.bozho.model.StatementsAA.StatementAA.class,
    bg.bozho.model.StatementsA.StatementA.class,
    bg.bozho.model.StatementsB.StatementB.class,
    bg.bozho.model.StatementsC.StatementC.class,
    bg.bozho.model.StatementsV.StatementV.class,
    bg.bozho.model.StatementsW.StatementW.class,
    bg.bozho.model.StatementsT.StatementT.class,
    bg.bozho.model.StatementsU.StatementU.class,
    bg.bozho.model.StatementsZ.StatementZ.class,
    bg.bozho.model.StatementsX.StatementX.class,
    bg.bozho.model.StatementsY.StatementY.class,
    bg.bozho.model.StatementsG.StatementG.class,
    bg.bozho.model.StatementsF.StatementF.class,
    bg.bozho.model.StatementsE.StatementE.class,
    bg.bozho.model.StatementsD.StatementD.class,
    bg.bozho.model.StatementsK.StatementK.class,
    bg.bozho.model.StatementsJ.StatementJ.class,
    bg.bozho.model.StatementsI.StatementI.class,
    bg.bozho.model.StatementsH.StatementH.class,
    bg.bozho.model.StatementsO.StatementO.class,
    bg.bozho.model.StatementsN.StatementN.class,
    bg.bozho.model.StatementsM.StatementM.class,
    bg.bozho.model.StatementsL.StatementL.class,
    bg.bozho.model.StatementsS.StatementS.class,
    bg.bozho.model.StatementsR.StatementR.class,
    bg.bozho.model.StatementsQ.StatementQ.class,
    bg.bozho.model.StatementsP.StatementP.class
})
public class StatementType {

    @XmlAttribute(name = "ActModeText")
    protected String actModeText;
    @XmlAttribute(name = "ActModeValue")
    protected String actModeValue;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "ActID")
    protected String actID;
    @XmlAttribute(name = "ActDate")
    protected String actDate;
    @XmlAttribute(name = "ActYear")
    protected String actYear;
    @XmlAttribute(name = "ActWithErasedPersonalData")
    protected String actWithErasedPersonalData;
    @XmlAttribute(name = "RecordID", required = true)
    protected int recordID;
    @XmlAttribute(name = "GroupID", required = true)
    protected int groupID;
    @XmlAttribute(name = "RecordIncomingNumber", required = true)
    protected String recordIncomingNumber;

    /**
     * Gets the value of the actModeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActModeText() {
        return actModeText;
    }

    /**
     * Sets the value of the actModeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActModeText(String value) {
        this.actModeText = value;
    }

    /**
     * Gets the value of the actModeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActModeValue() {
        return actModeValue;
    }

    /**
     * Sets the value of the actModeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActModeValue(String value) {
        this.actModeValue = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the actID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActID() {
        return actID;
    }

    /**
     * Sets the value of the actID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActID(String value) {
        this.actID = value;
    }

    /**
     * Gets the value of the actDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActDate() {
        return actDate;
    }

    /**
     * Sets the value of the actDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActDate(String value) {
        this.actDate = value;
    }

    /**
     * Gets the value of the actYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActYear() {
        return actYear;
    }

    /**
     * Sets the value of the actYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActYear(String value) {
        this.actYear = value;
    }

    /**
     * Gets the value of the actWithErasedPersonalData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActWithErasedPersonalData() {
        return actWithErasedPersonalData;
    }

    /**
     * Sets the value of the actWithErasedPersonalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActWithErasedPersonalData(String value) {
        this.actWithErasedPersonalData = value;
    }

    /**
     * Gets the value of the recordID property.
     * 
     */
    public int getRecordID() {
        return recordID;
    }

    /**
     * Sets the value of the recordID property.
     * 
     */
    public void setRecordID(int value) {
        this.recordID = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     */
    public int getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     */
    public void setGroupID(int value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the recordIncomingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordIncomingNumber() {
        return recordIncomingNumber;
    }

    /**
     * Sets the value of the recordIncomingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordIncomingNumber(String value) {
        this.recordIncomingNumber = value;
    }

}
