//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 04:34:28 PM EEST 
//


package bg.bozho.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubUICTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SubUICTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MainCircumstances"/>
 *     &lt;enumeration value="B1_Procura"/>
 *     &lt;enumeration value="B2_Branch"/>
 *     &lt;enumeration value="B3_Pledge_DD"/>
 *     &lt;enumeration value="B4_Pledge_TP"/>
 *     &lt;enumeration value="B5_Distraint_DD"/>
 *     &lt;enumeration value="B6_Liquidation"/>
 *     &lt;enumeration value="B7_ActualOwner"/>
 *     &lt;enumeration value="V1_Transfer"/>
 *     &lt;enumeration value="V2_Conversion"/>
 *     &lt;enumeration value="V3_Reorganization_K"/>
 *     &lt;enumeration value="Bankruptcy"/>
 *     &lt;enumeration value="Notes"/>
 *     &lt;enumeration value="G1_ActAnnouncement"/>
 *     &lt;enumeration value="AdditionalCircumstances"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SubUICTYPE", namespace = "http://www.registryagency.bg/schemas/deedv2")
@XmlEnum
public enum SubUICTYPE {


    /**
     * 
     * 						\u041e\u0441\u043d\u043e\u0432\u043d\u0438 \u0434\u0430\u043d\u043d\u0438
     * 					
     * 
     */
    @XmlEnumValue("MainCircumstances")
    MAIN_CIRCUMSTANCES("MainCircumstances"),

    /**
     * 
     * 						\u041f\u0440\u043e\u043a\u0443\u0440\u0430
     * 					
     * 
     */
    @XmlEnumValue("B1_Procura")
    B_1_PROCURA("B1_Procura"),

    /**
     * 
     * 						\u041a\u043b\u043e\u043d\u043e\u0432\u0435
     * 					
     * 
     */
    @XmlEnumValue("B2_Branch")
    B_2_BRANCH("B2_Branch"),

    /**
     * 
     * 						\u0417\u0430\u043b\u043e\u0433 \u043d\u0430 \u0434\u0440\u0443\u0436\u0435\u0441\u0442\u0432\u0435\u043d \u0434\u044f\u043b
     * 					
     * 
     */
    @XmlEnumValue("B3_Pledge_DD")
    B_3_PLEDGE_DD("B3_Pledge_DD"),

    /**
     * 
     * 						\u0417\u0430\u043b\u043e\u0433 \u043d\u0430 \u0442\u044a\u0440\u0433\u043e\u0432\u0441\u043a\u043e \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u044f\u0442\u0438\u0435
     * 					
     * 
     */
    @XmlEnumValue("B4_Pledge_TP")
    B_4_PLEDGE_TP("B4_Pledge_TP"),

    /**
     * 
     * 						\u0417\u0430\u043f\u043e\u0440 \u0432\u044a\u0440\u0445\u0443 \u0434\u0440\u0443\u0436\u0435\u0441\u0442\u0432\u0435\u043d \u0434\u044f\u043b
     * 					
     * 
     */
    @XmlEnumValue("B5_Distraint_DD")
    B_5_DISTRAINT_DD("B5_Distraint_DD"),

    /**
     * 
     * 						\u041b\u0438\u043a\u0432\u0438\u0434\u0430\u0446\u0438\u044f
     * 					
     * 
     */
    @XmlEnumValue("B6_Liquidation")
    B_6_LIQUIDATION("B6_Liquidation"),

    /**
     * 
     *             \u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u043d\u0438 \u0441\u043e\u0431\u0441\u0442\u0432\u0435\u043d\u0438\u0446\u0438
     *           
     * 
     */
    @XmlEnumValue("B7_ActualOwner")
    B_7_ACTUAL_OWNER("B7_ActualOwner"),

    /**
     * 
     * 						\u041f\u0440\u0435\u0445\u0432\u044a\u0440\u043b\u044f\u043d\u0435
     * 					
     * 
     */
    @XmlEnumValue("V1_Transfer")
    V_1_TRANSFER("V1_Transfer"),

    /**
     * 
     * 						\u041f\u0440\u0435\u043e\u0431\u0440\u0430\u0437\u0443\u0432\u0430\u043d\u0435
     * 					
     * 
     */
    @XmlEnumValue("V2_Conversion")
    V_2_CONVERSION("V2_Conversion"),

    /**
     * 
     * 						\u041f\u0440\u0435\u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e
     * 					
     * 
     */
    @XmlEnumValue("V3_Reorganization_K")
    V_3_REORGANIZATION_K("V3_Reorganization_K"),

    /**
     * 
     * 						\u041d\u0435\u0441\u044a\u0441\u0442\u043e\u044f\u0442\u0435\u043b\u043d\u043e\u0441\u0442
     * 					
     * 
     */
    @XmlEnumValue("Bankruptcy")
    BANKRUPTCY("Bankruptcy"),

    /**
     * 
     * 						\u0417\u0430\u0431\u0435\u043b\u0435\u0436\u043a\u0438
     * 					
     * 
     */
    @XmlEnumValue("Notes")
    NOTES("Notes"),

    /**
     * 
     * 						\u041e\u0431\u044f\u0432\u0435\u043d\u0438 \u0430\u043a\u0442\u043e\u0432\u0435
     * 					
     * 
     */
    @XmlEnumValue("G1_ActAnnouncement")
    G_1_ACT_ANNOUNCEMENT("G1_ActAnnouncement"),

    /**
     * 
     * 						\u0441\u043f\u0435\u0446\u0438\u0430\u043b\u0435\u043d \u043f\u0440\u0435\u0434\u043c\u0435\u0442 \u043d\u0430 \u0434\u0435\u0439\u043d\u043e\u0441\u0442
     * 					
     * 
     */
    @XmlEnumValue("AdditionalCircumstances")
    ADDITIONAL_CIRCUMSTANCES("AdditionalCircumstances");
    private final String value;

    SubUICTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubUICTYPE fromValue(String v) {
        for (SubUICTYPE c: SubUICTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
